export class Federazione{
    arrayfederazioni:any[] = [{sigla:"AECI",                
    descrizione:"Aero Club d'Italia"},  
    {sigla:"ACI",
    descrizione:"Automobile Club d'Italia"},
    {sigla: "FASI",
    descrizione:"Federazione Arrampicata Sportiva Italiana"},
    {sigla:"FIDAL",
    descrizione:"Federazione Italiana Atletica Leggera"},
    {sigla:"FIBa",
    descrizione:"Federazione Italiana Badminton"},
    {sigla:"FIBS",
    descrizione:"Federazione Italiana Baseball Softball"},
    {sigla:"FIB",
    descrizione:"Federazione Italiana Bocce"},
    {sigla:"FIDS",
    descrizione:"Federazione Italiana Danza Sportiva"},
    {sigla:"FIDASC",
    descrizione:"Federazione Italiana Discipline Armi Sportive da Caccia"},
    {sigla:"FIGC",
    descrizione:"Federazione Italiana Giuoco Calcio"},
    {sigla:"FICK",
    descrizione:"Federazione Italiana Canoa Kayak"},
    {sigla:"FIC",
    descrizione:"Federazione Italiana Canottaggio"},
    {sigla:"FCI",
    descrizione:"Federazione Ciclistica Italiana"},
    {sigla:"FICr",
    descrizione:"Federazione Italiana Cronometristi"},
    {sigla:"FGI",
    descrizione:"Federazione Ginnastica d'Italia"},
    {sigla:"FIG",
    descrizione:"Federazione Italiana Golf"},
    {sigla: "FIGH",
    descrizione:"Federazione Italiana Giuoco Handball"},
    {sigla:"FIGS",
    descrizione:"Federazione Italiana Giuoco Squash"},
    {sigla:"FIH",
    descrizione:"Federazione Italiana Hockey"},
    {sigla:"FISR",
    descrizione:"Federazione Italiana Sport Rotellistici"},
    {sigla:"FIJLKAM",
    descrizione:"Federazione Italiana Judo Lotta Karate Arti Marziali"},
    {sigla:"FMSI",
    descrizione:"Federazione Medico Sportiva Italiana"},
    {sigla:"FMI",
    descrizione:"Federazione Motociclistica Italiana"},
    {sigla:"FIM",
    descrizione:"Federazione Italiana Motonautica"},
    {sigla:"FIN",
    descrizione:"Federazione Italiana Nuoto"},
    {sigla:"FIP",
    descrizione:"Federazione Italiana Pallacanestro"},
    {sigla:"FIPAV",
    descrizione:"Federazione Italiana Pallavolo"},
    {sigla:"FIPM",
    descrizione:"Federazione Italiana Pentathlon Moderno"},
    {sigla:"FIPSAS",
    descrizione:"Federazione Italiana Pesca Sportiva E Attività Subacquee"},
    {sigla:"FIPE",
    descrizione:"Federazione Italiana Pesistica"},
    {sigla:"FPI",
    descrizione:"Federazione Pugilistica Italiana"},
    {sigla:"FIR",
    descrizione:"Federazione Italiana Rugby"},
    {sigla:"FIS",
    descrizione:"Federazione Italiana Scherma"},
    {sigla:"FISW",
    descrizione:"Federazione Italiana Sci Nautico e Wakeboard"},
    {sigla:"FISG",
    descrizione:"Federazione Italiana Sport del Ghiaccio"},
    {sigla:"FISE",
    descrizione:"Federazione Italiana Sport Equestri"},
    {sigla:"FISI",
    descrizione:"Federazione Italiana Sport Invernali"},
    {sigla:"FITA",
    descrizione:"Federazione Italiana Taekwondo"},
    {sigla:"FIT",
    descrizione:"Federazione Italiana Tennis"},
    {sigla:"FITET",
    descrizione:"Federazione Italiana Tennistavolo"},
    {sigla: "UITS",
    descrizione:"Unione Italiana Tiro a Segno"},
    {sigla:"FITAV",
    descrizione:"Federazione Italiana Tiro a Volo"},
    {sigla:"FITArco",
    descrizione:"Federazione Italiana Tiro con l'Arco"},
    {sigla:"FITRI",
    descrizione:"Federazione Italiana Triathlon"},
    {sigla:"FIV",
    descrizione:"Federazione Italiana Vela"}]
}


